# Copyright (C) 2025 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

default: true

MD013:
  line_length: 180
  code_blocks: false
  tables: false

MD033:
  allowed_elements:
    - details
    - summary
