# Copyright (C) 2023 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

default_language_version:
  python: python3 # Defaults to python2, so override it.

exclude: ^test/data
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
  # Formatters should be run late so that they can re-format any prior changes.
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length", "120", "--target-version", "py311"]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--py", "311"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.1
    hooks:
      - id: clang-format
        types_or: [c, c++]
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.22.2
    hooks:
      - id: gersemi
        exclude: ^cmake/modules/
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier
        language: node
        additional_dependencies: [prettier@3.6.2]
        types_or: [json, markdown, yaml]
        args: ["--write", "--ignore-unknown"]
