# Copyright (C) 2023 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  commands:
    - pip install -r docs/requirements.txt
    - make -C docs linkcheck
    - docs/update_index_links.py --root-dir "$PWD" --inplace
    - make -C docs html
    - make -C docs latexpdf
    - mkdir -p "$READTHEDOCS_OUTPUT/pdf"
    - cp -r docs/_build/html "$READTHEDOCS_OUTPUT/"
    - cp docs/_build/latex/hictk.pdf "$READTHEDOCS_OUTPUT/pdf/"

formats:
  - pdf
