# Copyright (C) 2023 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  commands:
    - pip install -r docs/requirements.txt
    - make -C docs html
    - make -C docs latexpdf
    - mkdir -p "$READTHEDOCS_OUTPUT"
    - cp -r docs/_build/* "$READTHEDOCS_OUTPUT/"

formats:
  - pdf
