# Copyright (C) 2024 Roberto Rossini <roberros@uio.no>
# SPDX-License-Identifier: MIT

name: Test compatibility with newer C++ standards

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/cppstd.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/scripts/**"
      - "test/units/**"
      - "utils/devel/build_dependencies.py"
      - "CMakeLists.txt"
      - "conanfile.py"

  pull_request:
    paths:
      - ".github/workflows/cppstd.yml"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build-deps-cpp20:
    name: Build Conan deps
    uses: paulsengroup/hictk/.github/workflows/build-conan-deps-linux.yml@89e2c2b5fff5bdabbd0f4df2b54ed66857d26008
    with:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-24.04-cxx-clang-21
      cppstd: 20
      build-type: Release

  build-deps-cpp23:
    name: Build Conan deps
    uses: paulsengroup/hictk/.github/workflows/build-conan-deps-linux.yml@89e2c2b5fff5bdabbd0f4df2b54ed66857d26008
    with:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-24.04-cxx-clang-21
      cppstd: 23
      build-type: Release

  build-project:
    runs-on: ubuntu-latest
    name: Build project
    needs:
      - build-deps-cpp20
      - build-deps-cpp23
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-24.04-cxx-clang-21
      options: "--user=root"

    env:
      CCACHE_DIR: "/opt/ccache-cache"
      CCACHE_COMPILERCHECK: "content"
      CCACHE_COMPRESSLEVEL: "1"
      CCACHE_MAXSIZE: "10G"
      TMPDIR: "/tmp/"

    strategy:
      fail-fast: false
      matrix:
        cppstd:
          - 20
          - 23

    steps:
      - uses: actions/checkout@v5

      - name: Fix permissions
        run: chown -R "$(id -u):$(id -g)" "$PWD"

      - name: Generate cache key
        id: cache-key
        run: |
          if [[ '${{ matrix.cppstd }}' == 20 ]]; then
            deps_cache_key='${{ needs.build-deps-cpp20.outputs.cache-key }}'
            deps_cache_path='${{ needs.build-deps-cpp20.outputs.tar }}'
          elif [[ '${{ matrix.cppstd }}' == 23 ]]; then
            deps_cache_key='${{ needs.build-deps-cpp23.outputs.cache-key }}'
            deps_cache_path='${{ needs.build-deps-cpp23.outputs.tar }}'
          else
            1>&2 echo 'Unknown cppstd "${{ matrix.cppstd }}"'
            exit 1
          fi

          deps_hash="$(echo "$deps_cache_key" | sha256sum | cut -f 1 -d ' ')"

          # This can be used by to always update a cache entry (useful e.g. for ccache)
          current_date="$(date '+%Y-%m-%d-%H:%M:%S')"

          ccache_key_prefix="ccache-cppstd-${{ matrix.cppstd }}-$deps_hash"
          ccache_key_prefix="$(echo "$ccache_key_prefix" |
                               tr -c '[:alnum:]._-' '-' |
                               sed 's/-\+/-/g' |
                               sed 's/-$//' |
                               tr '[:upper:]' '[:lower:]'
                             )"

          {
            echo "deps-key=${deps_cache_key}"
            echo "deps-path=${deps_cache_path}"
            echo "ccache-key=${ccache_key_prefix}-$GITHUB_REF-${current_date}"
            echo "ccache-restore-key-1=$ccache_key_prefix-$GITHUB_REF"
            echo "ccache-restore-key-2=$ccache_key_prefix"
          } | tee -a "$GITHUB_OUTPUT"

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.cache-key.outputs.deps-key }}
          path: ${{ steps.cache-key.outputs.deps-path }}
          fail-on-cache-miss: true

      - name: Unpack dependencies
        run: |
          tar -C "$TMPDIR" \
              --strip-components 1 \
              -xf '${{ steps.cache-key.outputs.deps-path }}'

      - name: Install Python headers
        run: |
          apt-get update
          apt-get install -y python3.12-dev

      - name: Configure project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release                       \
                -DCMAKE_C_STANDARD=17                            \
                -DCMAKE_CXX_STANDARD='${{ matrix.cppstd }}'      \
                -DCMAKE_C_COMPILER_FLAGS_RELEASE='-O2 -DDEBUG'   \
                -DCMAKE_CXX_COMPILER_FLAGS_RELEASE='-O2 -DDEBUG' \
                -DCMAKE_LINKER_TYPE=LLD                          \
                -DCMAKE_PREFIX_PATH="$TMPDIR/deps/cmake/"        \
                -DHICTK_ENABLE_TESTING=ON                        \
                -DHICTK_ENABLE_FUZZY_TESTING=OFF                 \
                -DHICTK_BUILD_TOOLS=OFF                          \
                -DHICTK_BUILD_EXAMPLES=ON                        \
                -DHICTK_DOWNLOAD_TEST_DATASET=OFF                \
                -DHICTK_ENABLE_GIT_VERSION_TRACKING=OFF          \
                -S .                                             \
                -B build

      - name: Restore Ccache folder
        id: cache-ccache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.cache-key.outputs.ccache-restore-key-1 }}
          restore-keys: ${{ steps.cache-key.outputs.ccache-restore-key-2 }}
          path: ${{ env.CCACHE_DIR }}

      - name: Reset Ccache stats
        run: ccache --zero-stats

      - name: Build project
        id: cmake-build
        run: |
          echo "start=$(date +%s)" >> "$GITHUB_OUTPUT"
          cmake --build build -j "$(nproc)"

      - name: Print Ccache statistics (pre-cleanup)
        run: |
          ccache --show-stats \
                 --show-compression \
                 --verbose

      - name: Cleanup Ccache folder
        run: |
          timestamp="$(date +%s)"
          time_delta="$(( timestamp - ${{ steps.cmake-build.outputs.start }} + 60 ))"
          ccache --evict-older-than="${time_delta}s"
          ccache --recompress=19 --recompress-threads="$(nproc)"
          ccache --cleanup --max-size 1G

      - name: Print Ccache statistics (post-cleanup)
        run: |
          ccache --show-stats \
                 --show-compression \
                 --verbose

      - name: Save Ccache folder
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-key.outputs.ccache-key }}
          path: ${{ env.CCACHE_DIR }}
        env:
          ZSTD_CLEVEL: 1

      - name: Generate list of stale cache entries
        id: stale-cache
        if: steps.cache-ccache.outputs.cache-matched-key != ''
        run: |
          fname='stale-cache-cppstd-${{ matrix.cppstd }}.txt'
          echo '${{ steps.cache-ccache.outputs.cache-matched-key }}' > "$fname"

          echo "name=$fname" | tee -a "$GITHUB_OUTPUT"

      - name: Upload stale cache entries
        if: steps.cache-ccache.outputs.cache-matched-key != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.stale-cache.outputs.name }}
          path: "${{ steps.stale-cache.outputs.name }}"
          if-no-files-found: error
          retention-days: 1

  purge-stale-ccache-entries:
    name: Purge stale CCache entries
    needs: [build-project]
    uses: paulsengroup/hictk/.github/workflows/purge-stale-ccache-entries.yml@0a18aef88705bbc2322b4fdd0ddde64d20f6e765
    permissions:
      contents: read
      actions: write

  cppstd-status-check:
    name: Status Check (cppstd)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build-project

    steps:
      - name: Collect job results
        if: needs.build-project.result != 'success'
        run: exit 1
