# Copyright (C) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Test compatibility with newer C++ standards

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/cppstd.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/scripts/**"
      - "test/units/**"
      - "CMakeLists.txt"
      - "conanfile.py"
    tags:
      - "v*.*.*"

  pull_request:
    paths:
      - ".github/workflows/cppstd.yml"
      - "cmake/**"
      - "examples/**"
      - "src/**"
      - "test/scripts/**"
      - "test/units/**"
      - "CMakeLists.txt"
      - "conanfile.py"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-deps:
    runs-on: ubuntu-latest
    name: Build dependencies
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-24.04-cxx-clang-19
      options: "--user=root"

    outputs:
      cache-key: ${{ steps.generate-cache-key.outputs.conan-key }}

    env:
      CONAN_HOME: "/opt/conan/"

    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: Generate cache key
        id: generate-cache-key
        run: |
          hash="${{ hashFiles('conanfile.py') }}"

          echo "conan-key=conan-cppstd-$hash" | tee -a "$GITHUB_OUTPUT"

      - name: Restore Conan cache
        id: cache-conan
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.generate-cache-key.outputs.conan-key }}
          path: "${{ env.CONAN_HOME }}/p"
          lookup-only: true

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source
          conan remove --confirm "*"

      - name: Copy Conan settings
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          if [ ! -f "$CONAN_HOME/settings.yml" ]; then
            cp "/root/.conan2/settings.yml" "$CONAN_HOME"
          fi

      - name: Install build dependencies (c++20)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan install .                        \
             --build=missing                     \
             -pr:b="$CONAN_DEFAULT_PROFILE_PATH" \
             -pr:h="$CONAN_DEFAULT_PROFILE_PATH" \
             -s build_type=Debug                 \
             -s compiler.libcxx=libstdc++11      \
             -s compiler.cppstd=20

      - name: Install build dependencies (c++23)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan install .                        \
             --build=missing                     \
             -pr:b="$CONAN_DEFAULT_PROFILE_PATH" \
             -pr:h="$CONAN_DEFAULT_PROFILE_PATH" \
             -s build_type=Debug                 \
             -s compiler.libcxx=libstdc++11      \
             -s compiler.cppstd=23

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan cache clean "*" --build
          conan cache clean "*" --download
          conan cache clean "*" --source

      - name: Save Conan cache
        uses: actions/cache/save@v4
        if: steps.cache-conan.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.generate-cache-key.outputs.conan-key }}
          path: "${{ env.CONAN_HOME }}/p"

  build-project:
    runs-on: ubuntu-latest
    name: Build project
    needs: [build-deps]
    container:
      image: ghcr.io/paulsengroup/ci-docker-images/ubuntu-24.04-cxx-clang-19
      options: "--user=root"

    env:
      CCACHE_DIR: "/opt/ccache-cache"
      CCACHE_COMPILERCHECK: "content"
      CCACHE_COMPRESSLEVEL: "1"
      CCACHE_MAXSIZE: "150M"
      CONAN_HOME: "/opt/conan/"

    strategy:
      fail-fast: false
      matrix:
        cppstd:
          - 20
          - 23

    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          chown -R $(id -u):$(id -g) $PWD

      - name: Generate cache key
        id: generate-cache-key
        run: |
          conanfile_hash="${{ hashFiles('conanfile.py') }}"

          # This can be used by to always update a cache entry (useful e.g. for ccache)
          current_date="$(date '+%s')"

          ccache_key_prefix="ccache-cppstd-${{ matrix.cppstd }}-$conanfile_hash"

          echo "ccache-key=${ccache_key_prefix}-${current_date}" | tee -a "$GITHUB_OUTPUT"
          echo "ccache-restore-key=$ccache_key_prefix" | tee -a "$GITHUB_OUTPUT"

      - name: Restore Conan cache
        id: cache-conan
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.build-deps.outputs.cache-key }}
          path: "${{ env.CONAN_HOME }}/p"
          fail-on-cache-miss: true

      - name: Copy Conan settings
        run: |
          if [ ! -f "$CONAN_HOME/settings.yml" ]; then
            cp "/root/.conan2/settings.yml" "$CONAN_HOME"
          fi

      - name: Install build dependencies
        run: |
          conan install .                            \
             --build=never                           \
             -pr:b="$CONAN_DEFAULT_PROFILE_PATH"     \
             -pr:h="$CONAN_DEFAULT_PROFILE_PATH"     \
             -s build_type=Debug                     \
             -s compiler.libcxx=libstdc++11          \
             -s compiler.cppstd=${{ matrix.cppstd }} \
             --output-folder=build

      - name: Install Python headers
        run: |
          apt-get update
          apt-get install -y python3.12-dev

      - name: Configure project
        run: |
          find src test \
            -type f \
            -name CMakeLists.txt \
            -exec sed -i 's/set(CMAKE_CXX_STANDARD 17)/set(CMAKE_CXX_STANDARD ${{ matrix.cppstd }})/' {} +

          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_PREFIX_PATH="$PWD/build" \
                -DHICTK_ENABLE_TESTING=ON \
                -DHICTK_ENABLE_FUZZY_TESTING=ON \
                -DHICTK_BUILD_TOOLS=OFF \
                -DHICTK_BUILD_EXAMPLES=ON \
                -DHICTK_DOWNLOAD_TEST_DATASET=OFF \
                -DHICTK_ENABLE_GIT_VERSION_TRACKING=OFF \
                -S . \
                -B build

      - name: Restore Ccache folder
        id: cache-ccache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.generate-cache-key.outputs.ccache-restore-key }}
          path: ${{ env.CCACHE_DIR }}

      - name: Reset Ccache stats
        run: ccache --zero-stats

      - name: Build project
        run: cmake --build build -j $(nproc)

      - name: Print Ccache statistics (pre-cleanup)
        run: |
          ccache --show-stats \
                 --show-compression \
                 --verbose

      - name: Cleanup Ccache folder
        run: |
          ccache --evict-older-than=14400s # 4h
          ccache --recompress=19 --recompress-threads="$(nproc)"
          ccache --cleanup

      - name: Print Ccache statistics (post-cleanup)
        run: |
          ccache --show-stats \
                 --show-compression \
                 --verbose

      - name: Save Ccache folder
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.generate-cache-key.outputs.ccache-key }}
          path: ${{ env.CCACHE_DIR }}
        env:
          ZSTD_CLEVEL: 1

  cppstd-status-check:
    name: Status Check (cppstd)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build-deps
      - build-project

    steps:
      - name: Collect job results
        if: |
          needs.build-deps.result != 'success' ||
          needs.build-project.result != 'success'
        run: exit 1
