# Copyright (C) 2024 Roberto Rossini <roberros@uio.no>
# SPDX-License-Identifier: MIT

name: Run pre-commit.ci lite

on:
  push:
    branches: [main]

  pull_request:

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  pre-commit-ci:
    runs-on: ubuntu-latest
    name: Run pre-commit.ci lite

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pre-commit-ci/lite-action@v1.0.3
